/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.guess;

import com.tw.cn.cap.gtb.guess.guess.GetTipImplement;
import com.tw.cn.cap.gtb.guess.util.GetNum;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        String guessNum = GetNum.getGuessNum();
        List<Integer> randomNum = GetNum.getRandomNum();
        System.out.println("The random number is: ");
        System.out.println(randomNum);
        GetTipImplement getTipImplement = new GetTipImplement();
        String tipResult = getTipImplement.getTipResult(randomNum, guessNum);
        System.out.println(tipResult);
    }
}
